apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-postgres-data
  namespace: cvat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi
